name: Build and Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build service with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Test service with Maven
        run: mvn test --file pom.xml

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1

      - name: Change to frontend directory
        run: cd src/deliveryrouting
      
      - name: Install node modules
        run: npm install

      - name: Build frontend with NPM
        run: npm run build
      
      - name: Test frontend with NPM
        run: npm test -- --watchAll=false
